sonar.projectKey=adlandh_echo-dump-body-skipper
sonar.organization=adlandh

sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/*_test.go

sonar.cpd.exclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out
